[build-system]
requires = ["setuptools >=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg"
version = "0.0.1"

description = "pkg"

authors = [
  { name = "Michael Bleher", email = "mbleher@mathi.uni-heidelberg.de" },
]

license = { file = "LICENSE" }
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

requires-python = ">=3.11"
dependencies = [
  "numpy>=2.1.3",
  "scipy>=1.14.1",
  "scikit-learn>=1.5.2",
  "matplotlib>=3.9.2",
]

[dependency-groups]
dev = [
  "black>=23.12.1",
  "pre-commit>=3.5.0",
  "pytest>=7.4.3",
]
